---
nodes:
  - name: firstnode
    host: firstnode.example.com
    port: 22
    user: dev
    logs:
      - type: rails
        file: /srv/railsapp/shared/log/production.log
      - type: nginx
        file: /var/log/nginx/access.log
