---
webdir: /var/www/logring
nodes:
  firstnode.example.com:
    name: firstnode
    user: dev
    # port: 22
    path: ~/logring
    logs:
      rails:
        - /srv/railsapp/shared/log/production.log
      nginx:
        - /var/log/nginx/access.log
