---
webdir: www              # dir local to logring installation where to save static web pages
logdir: log              # dir local to logring or STDOUT to have logging on console
loglevel: info           # can be debug, info, warn, error, fatal
install_url: https://raw.github.com/eduvo/logring/master/install
nodes:
  firstnode.example.com: # hostname that you can ssh to
    name: firstnode      # name used by logring in its cli
    user: dev            # user that you can ssh with
    # port: 22           # port you need to use for ssh, if absent 22 is used
    path: ~/logring      # remote path where cache files are stored
    sudo: true           # can we or can we not use sudo there
    logs:
      web:
        report: nginx
        file: /var/log/nginx/access.log
      app:
        report: rails
        file: /srv/railsapp/shared/log/sandbox.log
